<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260811075354 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE sales_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contractor_id INT NOT NULL, created_by INT NOT NULL, type VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, approved_by INT DEFAULT NULL, approved_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, parent_quote_id INT DEFAULT NULL, seller_snapshot JSON DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE sales_document');
    }
}
